# 資料前處理(Label encoding、 One hot encoding)
這兩個編碼方式的目的是為了將類別 (categorical)或是文字(text)的資料轉換成數字，而讓程式能夠更好的去理解及運算。
> Label encoding : 把每個類別 mapping 到某個整數，不會增加新欄位

> One hot encoding : 為每個類別新增一個欄位，用 0/1 表示是否

![](images/Encoder.PNG)


## Encoding Categorical features (or label)
![](images/Encoding.PNG)

In [3]:
import pandas as pd
import numpy as np

In [17]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});
df

  blood     Y       Z
0     A  high     NaN
1     B   low     NaN
2    AB  high -1196.0
3     O   mid    72.0
4     B   mid    83.0

# 方法一：sklearn - label encoder + onehot encoder
>onehot encoder要用2D array，若維度所以要用reshape(-1,1)<br>
>onehot encoder要數字，若資料文文字要先用label encoder轉數字

In [18]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
encoder_Y=encoder.fit_transform(df['blood'])
print(encoder_Y)
df["blood"]=encoder_Y #因為轉換後有順序，可以直接丟回去frame!
df

"""您可能會想：「為什麼不能直接用 OneHotEncoder().fit(...) 就好，非得要取個名字叫 onehot 呢？」

這牽涉到機器學習裡非常重要的一個觀念：狀態與記憶 (State & Memory)。

這台 onehot 機器在運作時分為兩個階段：

學習階段 (Fit)： 當您給它看您的資料（例如：台北、台中、高雄），這台 onehot 機器會在它的肚子裡**「記住」**這些類別的順序（例如：台北是第 0 欄，台中是第 1 欄）。

轉換階段 (Transform)： 接下來，您要它把資料轉換成 0 和 1 的矩陣。

如果您沒有用一個變數（像是 onehot）把它存起來，這台機器在做完第一步（看資料）之後，就會立刻被電腦的資源回收車載走銷毀！等您要進行第二步轉換時，它已經忘記剛才學過的對照表了。

👉 結論： 寫下 onehot = OneHotEncoder()，就是為了把這台具有「學習記憶」的實體機器留在您的桌面上，隨時聽候您的差遣！"""

[0 2 1 3 2]

'您可能會想：「為什麼不能直接用 OneHotEncoder().fit(...) 就好，非得要取個名字叫 onehot 呢？」\n\n這牽涉到機器學習裡非常重要的一個觀念：狀態與記憶 (State & Memory)。\n\n這台 onehot 機器在運作時分為兩個階段：\n\n學習階段 (Fit)： 當您給它看您的資料（例如：台北、台中、高雄），這台 onehot 機器會在它的肚子裡**「記住」**這些類別的順序（例如：台北是第 0 欄，台中是第 1 欄）。\n\n轉換階段 (Transform)： 接下來，您要它把資料轉換成 0 和 1 的矩陣。\n\n如果您沒有用一個變數（像是 onehot）把它存起來，這台機器在做完第一步（看資料）之後，就會立刻被電腦的資源回收車載走銷毀！等您要進行第二步轉換時，它已經忘記剛才學過的對照表了。\n\n👉 結論： 寫下 onehot = OneHotEncoder()，就是為了把這台具有「學習記憶」的實體機器留在您的桌面上，隨時聽候您的差遣！'

In [19]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder() #Onehotendoing只能用再array 所以要轉檔
print(type(df["blood"]))
d=np.array(df["blood"])
d.shape
onehot_df=onehot.fit_transform(d.reshape(-1,1)).toarray() #OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
onehot_df

<class 'pandas.core.series.Series'>

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

## One hot encoding
One Hot encoding的編碼邏輯為將類別拆成多個行(column)，每個列中的數值由1、0替代，當某一列的資料存在的該行的類別則顯示1，反則顯示0。

然在指定column進行編碼的情形下，One hot encoding<b>無法直接對字串進行編碼，必須先透過Label encoding將字串以數字取代後再進行One hot encoding處理。</b>

> categorical_features = [0]: 表示欲在data上執行One hot encoding的index為0

> data_le: 為經過Label encoding編碼的資料(註:OneHotEncoder的輸入要為2-D array，而Label encoding為1-D array)

OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
從結果可以知道，數字0的column 代表的是A、數字1的column 代表的是B，而數字2的column 代表的是AB。
除了轉換字串外，One hot encoding也可以轉換數字。在此處的data就不需要先經過Label encoding編碼

```python
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 
   
# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])],  #做的欄位
                                      remainder='passthrough') 
  
data = np.array(columnTransformer.fit_transform(data), dtype = str) 
```

In [20]:
# importing one hot encoder from sklearn 
# There are changes in OneHotEncoder class 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough')

In [24]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import ColumnTransformer 

# creating one hot encoder object with categorical feature 0 
# indicating the first column 
columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough')  #有沒有reminder會刪除其他沒有執行的變項
data = np.array(columnTransformer.fit_transform(df), dtype = str) 
data

data_le=pd.DataFrame(data)
data_le

     0    1    2    3     4        5
0  1.0  0.0  0.0  0.0  high      nan
1  0.0  0.0  1.0  0.0   low      nan
2  0.0  1.0  0.0  0.0  high  -1196.0
3  0.0  0.0  0.0  1.0   mid     72.0
4  0.0  0.0  1.0  0.0   mid     83.0

# 方法二：Keras - label encoder + to_categorical
>to_categorical要數字，若資料文文字要先用label encoder轉數字

In [46]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical # 修正 Keras 匯入語法

df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]});

# label encoder 
encoder=LabelEncoder()
encoder_Y=encoder.fit_transform(df['blood'])
print(encoder_Y)
df["blood"]=encoder_Y #因為轉換後有順序，可以直接丟回去frame!
df

# convert integers to one hot encoding
"""keras_onehot=np_utils.to_categorical(encoder_Y)
keras_onehot"""
keras_onehot = to_categorical(encoder_Y)
print("\nOne-Hot Encoding 轉換結果:")
print(keras_onehot)

[0 2 1 3 2]

One-Hot Encoding 轉換結果:
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

## 方法三：pd.get_dummies方法
![](images/Encoding_pd.PNG)
pd.get_dummies(df)
>get_dummies可以直接轉字串，反而無法轉換數字<br>
>get_dummies沒指定columns，會全部轉換

In [39]:
df = pd.DataFrame({'blood':['A','B','AB','O','B'], 
                   'Y':['high','low','high','mid','mid'],
                   'Z':[np.nan,np.nan,-1196,72,83]})
df1=pd.get_dummies(df)
print(df1)
df3=pd.get_dummies(df,dtype=int)
print(df3)

df2=pd.get_dummies(df['blood'], dtype=int)
print(df2)

        Z  blood_A  blood_AB  blood_B  blood_O  Y_high  Y_low  Y_mid
0     NaN     True     False    False    False    True  False  False
1     NaN    False     False     True    False   False   True  False
2 -1196.0    False      True    False    False    True  False  False
3    72.0    False     False    False     True   False  False   True
4    83.0    False     False     True    False   False  False   True
        Z  blood_A  blood_AB  blood_B  blood_O  Y_high  Y_low  Y_mid
0     NaN        1         0        0        0       1      0      0
1     NaN        0         0        1        0       0      1      0
2 -1196.0        0         1        0        0       1      0      0
3    72.0        0         0        0        1       0      0      1
4    83.0        0         0        1        0       0      0      1
   A  AB  B  O
0  1   0  0  0
1  0   0  1  0
2  0   1  0  0
3  0   0  0  1
4  0   0  1  0

## 練習一：sklearn - label encoder + onehot encoder
下面的資料可以看到country那欄皆為字串， 大部分的模型都是基於數學運算，字串無法套入數學模型進行運算，<br>
在此先對其進行Label encoding編碼，我們從 sklearn library中導入 LabelEncoder class，對第一行資料進行fit及transform並取代之。

In [56]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data


encoder=LabelEncoder()
encoder_Y=encoder.fit_transform(data['Country'])
print(encoder_Y)
data["Country"]=encoder_Y #因為轉換後有順序，可以直接丟回去frame!

onehot=OneHotEncoder() #Onehotendoing只能用再array 所以要轉檔
print(type(data["Country"]))
d=np.array(data["Country"])
d.shape
onehot_df=onehot.fit_transform(d.reshape(-1,1)).toarray() #OneHotEncoder會轉出scipy.csr_matrix資料結構用.toarray()轉array
onehot_df

columnTransformer = ColumnTransformer([('encoder', 
                                        OneHotEncoder(), 
                                        [0])], 
                                      remainder='passthrough')  #有沒有reminder會刪除其他沒有執行的變項
data = np.array(columnTransformer.fit_transform(df), dtype = str) 
print(data)

data_le=pd.DataFrame(data)
print(data_le)

[2 0 1 0 1 2]
<class 'pandas.core.series.Series'>
[['1.0' '0.0' '0.0' '0.0' 'high' 'nan']
 ['0.0' '0.0' '1.0' '0.0' 'low' 'nan']
 ['0.0' '1.0' '0.0' '0.0' 'high' '-1196.0']
 ['0.0' '0.0' '0.0' '1.0' 'mid' '72.0']
 ['0.0' '0.0' '1.0' '0.0' 'mid' '83.0']]
     0    1    2    3     4        5
0  1.0  0.0  0.0  0.0  high      nan
1  0.0  0.0  1.0  0.0   low      nan
2  0.0  1.0  0.0  0.0  high  -1196.0
3  0.0  0.0  0.0  1.0   mid     72.0
4  0.0  0.0  1.0  0.0   mid     83.0

## 練習二：Keras - label encoder + to_categorical

In [55]:
from sklearn.preprocessing import LabelEncoder
#from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical # 修正 Keras 匯入語法

country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
print(data)


# label encoder 
encoder=LabelEncoder()
encoder_Y=encoder.fit_transform(data['Country'])
print(encoder_Y)
data["Country"]=encoder_Y #因為轉換後有順序，可以直接丟回去frame!
print(data)

# convert integers to one hot encoding
"""keras_onehot=np_utils.to_categorical(encoder_Y)
keras_onehot"""
keras_onehot = to_categorical(encoder_Y)
print("\nOne-Hot Encoding 轉換結果:")
print(keras_onehot)

# --- 以下是放回 DataFrame 的新增步驟 ---
# 1. 取得原來的類別名稱 (這會自動依照 0, 1, 2 對應 'Australia', 'Ireland', 'Taiwan')
category_names = encoder.classes_

# 2. 將 keras_onehot 陣列轉換成新的 DataFrame，並為欄位命名 (例如: Country_Taiwan)
onehot_df = pd.DataFrame(keras_onehot, columns=[f"Country_{name}" for name in category_names])

# 3. 刪除原本會造成模型誤判的 'Country' 數字欄位
data = data.drop('Country', axis=1)

# 4. 將原本的 data 與新的 onehot_df 橫向合併 (axis=1 代表左右合併)
final_data = pd.concat([data, onehot_df], axis=1)

print("\n最終合併後的 DataFrame:")
print(final_data)

     Country  Age  Salary
0     Taiwan   25   20000
1  Australia   30   32000
2    Ireland   45   59000
3  Australia   35   60000
4    Ireland   22   43000
5     Taiwan   36   52000
[2 0 1 0 1 2]
   Country  Age  Salary
0        2   25   20000
1        0   30   32000
2        1   45   59000
3        0   35   60000
4        1   22   43000
5        2   36   52000

One-Hot Encoding 轉換結果:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

最終合併後的 DataFrame:
   Age  Salary  Country_Australia  Country_Ireland  Country_Taiwan
0   25   20000                0.0              0.0             1.0
1   30   32000                1.0              0.0             0.0
2   45   59000                0.0              1.0             0.0
3   35   60000                1.0              0.0             0.0
4   22   43000                0.0              1.0             0.0
5   36   52000                0.0              0.0             1.0

## 練習三：Pandas.get_dummies
>　get_dummies : 僅能將字串轉換為One hot encoding表示形式， 沒指定columns會全部轉換。

In [51]:
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
print(data)

df1=pd.get_dummies(data)
print(df1)
df3=pd.get_dummies(data,dtype=int)
print(df3)
df2=pd.get_dummies(data['Country'], dtype=int)
print(df2)

     Country  Age  Salary
0     Taiwan   25   20000
1  Australia   30   32000
2    Ireland   45   59000
3  Australia   35   60000
4    Ireland   22   43000
5     Taiwan   36   52000
   Age  Salary  Country_Australia  Country_Ireland  Country_Taiwan
0   25   20000              False            False            True
1   30   32000               True            False           False
2   45   59000              False             True           False
3   35   60000               True            False           False
4   22   43000              False             True           False
5   36   52000              False            False            True
   Age  Salary  Country_Australia  Country_Ireland  Country_Taiwan
0   25   20000                  0                0               1
1   30   32000                  1                0               0
2   45   59000                  0                1               0
3   35   60000                  1                0               0
4   22   43000                  0                1               0
5   36   52000                  0                0               1
   Australia  Ireland  Taiwan
0          0        0       1
1          1        0       0
2          0        1       0
3          1        0       0
4          0        1       0
5          0        0       1